#!/bin/bash
# https://github.com/pikpikcu
# twitter: @sec715

# Faforit Colors
BK=$(tput setaf 0) # Black
RD=$(tput setaf 1) # Red
GR=$(tput setaf 2) # Green
YW=$(tput setaf 3) # Yellow
BL=$(tput setaf 4) # blue
PP=$(tput setaf 5) # purple
CY=$(tput setaf 6) # Cyan
WH=$(tput setaf 7) # White
AB=$(tput setaf 8) # abuabu
MR=$(tput setaf 9) # merahmuda
GR1=$(tput setaf 10) # greenblink
KN=$(tput setaf 11) #kuning
BL1=$(tput setaf 12) # birublink
PK=$(tput setaf 13) # pink
BLC=$(tput setaf 16) #black 
BG=$(tput setab 11) 
NT=$(tput sgr0) # Netral
BD=$(tput bold) # Bold

url="$1"

banner(){ 
    echo -e  "${CY}
    ▄▄▄  ▄▄▄ ..▄▄ · ▪  • ▌ ▄ ·. 
    ▀▄ █·▀▄.▀·▐█ ▀. ██ ·██ ▐███▪
    ▐▀▀▄ ▐▀▀▪▄▄▀▀▀█▄▐█·▐█ ▌▐▌▐█·
    ▐█•█▌▐█▄▄▌▐█▄▪▐█▐█▌██ ██▌▐█▌
    .▀  ▀ ▀▀▀  ▀▀▀▀ ▀▀▀▀▀  █▪▀▀▀
            [[ Recon Simple! ]]
\n"
}

url(){
    echo -e  "\n${RD}[${GR}+${RD}] ${GR1}START ON Target URLS ${NT}$url..${YW}🔍"
    sleep 3
    echo -e  "${RD}[${GR}!${RD}] ${CY}Searching For Sub-Domains..${YW}🔍"
    echo -e  "${RD}[${BL}*${RD}] ${KN}Starting Sub-Domains For assetfinder..${YW}🔍"
    assetfinder --subs-only $url | sort -u | tee -a > $out/$url-assetfinder.txt
    echo -e  "${RD}[${GR}!${RD}] ${CY}Found Sub-Domains For assetfinder: ${KN}$(cat $out/$url-assetfinder.txt | wc -l)"
    echo -e  "${RD}[${BL}*${RD}] ${KN}Starting Sub-Domains For subfinder..${YW}🔍"
    subfinder -silent -d $url | sort -u | tee -a > $out/$url-subfinder.txt
    echo -e  "${RD}[${GR}!${RD}] ${CY}Found Sub-Domains For subfinder: ${KN}$(cat $out/$url-subfinder.txt | wc -l)"
    echo -e  "${RD}[${BL}*${RD}] ${KN}Starting Sub-Domains For amass..${YW}🔍"
    amass enum -src -ip -active -brute -d $url > $out/$url-amas.txt
    cat $out/$url-amas.txt | grep -Po "((http|https):\/\/)?(([\w.-]*)\.([\w]*)\.([A-z]))\w+" > $out/$url-amass.txt
    echo -e  "${RD}[${GR}!${RD}] ${CY}Found Sub-Domains For amass: ${KN}$(cat $out/$url-amass.txt | wc -l)"
    echo -e  "${RD}[${BL}*${RD}] ${YW}Finall Subdomains..${YW}"
    cat $out/$url-assetfinder.txt $out/$url-subfinder.txt $out/$url-amass.txt | sort -u > $out/$url-final.txt
    rm -rf $out/$url-assetfinder.txt $out/$url-subfinder.txt $out/$url-amass.txt $out/$url-amas.txt
    echo -e  "${RD}[${BL}+${RD}] ${GR1}Done Total Subdomain: ${KN}$(cat $out/$url-final.txt | wc -l)"
    echo -e  "${CY}[!]${GR} The Following sub-domains are Scanned..."
        while read -r line;do
            r=`nslookup $line | awk '/^Address: / { print $2 }'`
            if [ "$r" == "" ];then
                echo -e  "${RD}[!]${NT} $line ${RD}❌" | tee $out/$url-notalive.txt
            else
                file_exist=$(cat $out/$url-final.txt | grep -c "$r")
                if [ $file_exist -eq 0 ]; then  
                    echo -e  "${CY}[*]${NT} $line ${GR}✅" | tee $out/$url-alivee.txt
                fi
            fi
        done < "$out/$url-final.txt"
        cat $out/$url-alivee.txt | grep -Po "((http|https):\/\/)?(([\w.-]*)\.([\w]*))" > $out/$url-alive.txt
        rm -rf $out/$url-alivee.txt
    echo -e  "${RD}[${GR}*${RD}] ${GR}DONE SCAN SUBDOMAIN......."
    sleep 3
    echo -e  "${RD}[${GR}!${RD}] ${GR}Find IP for SUBDOMAIN..${YW}🔍"
    while read -r line;do
            r=`dig $line +short`
            if [ "$r" == "" ];then
                echo -e  "${RD}[!]${NT} $line ${RD}❌" 
            else
                file_exist=$(cat $out/$url-alive.txt | grep -c "$r")
                if [ $file_exist -eq 0 ]; then  
                    echo -e  "${CY}[*] ${YW}Domain: ${NT}$line ${PP}$r ${GR}✅" 
                fi 
            fi
    done < "$out/$url-alive.txt"
    echo -e  "${RD}[${GR}!${RD}] ${GR}DONE CHECK IP SUBDOMAIN......."
    sleep 3
    echo -e  "${RD}[${GR}!${RD}] ${GR}CHECK PORT OPEN..${YW}🔍"
    while read -r line;do
            r=`nmap $line | grep "tcp"`
            if [ "$r" == "" ];then
                echo -e  "${RD}[!]${NT} $line ${RD}Error"
            else
                file_exist=$(cat $out/$url-alive.txt | grep -c "$r")
                if [ $file_exist -eq 0 ]; then  
                    echo -e  "${CY}[*]${YW} $line ${NT} \n$r \n"
                fi 
            fi
    done < "$out/$url-alive.txt"
    echo -e "${RD}[${GR}*${RD}] ${GR}DONE CHECK PORT OPEN......."
    sleep 3
    echo -e "${RD}[${GR}*${RD}] ${GR}START REVERSE DNS..${YW}🔍"
    while read -r line;do
            r=`curl -s https://api.hackertarget.com/reversedns/?q=$line`
            if [ "$r" == "" ];then
                echo -e  "${RD}[!]${NT} $line ${RD}Error"
            else
                file_exist=$(cat $out/$url-alive.txt| grep -c "$r")
                if [ $file_exist -eq 0 ]; then  
                    echo -e  "${CY}[*]${YW}Domain $line ${NT} \n$r"
                fi 
            fi
    done < "$out/$url-alive.txt"
    echo -e "${RD}[${GR}*${RD}] ${GR}START REVERSEIPLOOKUP..${YW}🔍"
    while read -r line;do
            r=`curl -s https://api.hackertarget.com/reverseiplookup/?q=$line`
            if [ "$r" == "" ];then
                echo -e  "${RD}[!]${NT} $line ${RD}Error"
            else
                file_exist=$(cat $out/$url-alive.txt | grep -c "$r")
                if [ $file_exist -eq 0 ]; then  
                    echo -e  "${CY}[*]${YW}Domain $line ${NT} \n$r"
                fi 
            fi
    done < "$out/$url-alive.txt"
    echo -e "${RD}[${GR}*${RD}] ${GR}START DNSLOOKUP..${YW}🔍"
    while read -r line;do
            r=`curl -s https://api.hackertarget.com/dnslookup/?q=$line`
            if [ "$r" == "" ];then
                echo -e  "${RD}[!]${NT} $line ${RD}Error"
            else
                file_exist=$(cat $out/$url-alive.txt | grep -c "$r")
                if [ $file_exist -eq 0 ]; then  
                    echo -e  "${CY}[*]${YW}Domain $line ${NT} \n$r"
                fi 
            fi
    done < "$out/$url-alive.txt"
    echo -e "${RD}[${GR}*${RD}] ${GR}START SUBNETLOOKUP..${YW}🔍"
    while read -r line;do
            r=`curl -s https://api.hackertarget.com/subnetcalc/?q=$line`
            if [ "$r" == "" ];then
                echo -e  "${RD}[!]${NT} $line ${RD}Error"
            else
                file_exist=$(cat $out/$url-alive.txt | grep -c "$r")
                if [ $file_exist -eq 0 ]; then  
                    echo -e  "${CY}[*]${YW}Domain $line ${NT} \n$r"
                fi 
            fi
    done < "$out/$url-alive.txt"
    echo -e "${RD}[${GR}*${RD}] ${GR}START EXTRACKLINKS..${YW}🔍"
    for i in $(cat $out/$url-alive.txt | parallel -j50 -q lynx -listonly -dump );do 
        file_exist=$(cat $out/$url-alive.txt | grep -c "$i")
        if [ $file_exist -eq 0 ]; then  
            echo -e  "${CY}[*]${YW} $i ${NT}"
        fi 
    done 
    echo -e "${RD}[${GR}*${RD}]${GR} Aquatone Screenshot"
    cat $out/$url-alive.txt | aquatone -screenshot-timeout 10 -out $out/screenshots/
    exit 1
}
if [[ -z "$url" ]];
    then
    banner
    echo -e  "\t\tUSAGE:"
    echo -e  "\t\t\t$0 -u example.com\n"
else 
while true;do
    case $url in 
        "-u" | "--url") url=$2
                banner
                out="$url"
                mkdir -p $out
                url $url
        ;;
    esac
done
fi
